// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwpvlrwzyuqxvuegzdqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3cHZscnd6eXVxeHZ1ZWd6ZHFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTk0NTQsImV4cCI6MjA2ODA3NTQ1NH0.o25gKqLDswpLI45urC4LX70_F1i4DMC3DwWLliB8JRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});